[project]
name = "smartwallet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.26.0",
    "aiosqlite>=0.22.1",
    "apscheduler>=3.11.2",
    "cachetools>=7.1.0",
    "dotenv>=0.9.9",
    "pandas>=3.0.1",
    "pdfplumber>=0.11.9",
    "pydantic-settings>=2.14.0",
    "pytesseract>=0.3.13",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "pyyaml>=6.0.3",
    "redis>=7.4.0",
    "scikit-learn>=1.8.0",
    "sentence-transformers>=5.4.1",
    "structlog>=25.5.0",
]
