YAML_CATEGORIES = "infrastructure/knowledge_base/yaml/knowledge_base.yml"
SQLITE_USERS = "infrastructure/database/db/users_db.sqlite3"
SQLITE_TRANSACTIONS = "infrastructure/database/db/transactions_db.sqlite3"
SQLITE_GOALS = "infrastructure/database/db/goals_db.sqlite3"
DATASET_PATH = "infrastructure/ml/classifier/dataset.csv"
MODEL_PATH = "infrastructure/ml/dumps/model.joblib"
VECTORIZER_PATH = "infrastructure/ml/dumps/vectorizer.joblib"
YAML_ADVICES = "infrastructure/knowledge_base/yaml/advices.yml"
