from abc import ABC, abstractmethod


class BaseGoalsRepository:
    @abstractmethod
    async def save_goal() -> None: ...
    @abstractmethod
    async def get_all_user_goals() -> None: ...
    @abstractmethod
    async def update_goal() -> None: ...
    @abstractmethod
    async def change_goal_text() -> None: ...
    @abstractmethod
    async def get_goal_attrs() -> None: ...
    @abstractmethod
    async def delete_goal() -> None: ...
    @abstractmethod
    async def get_user_goals_count() -> None: ...
    @abstractmethod
    async def get_users() -> None: ...
