from abc import ABC, abstractmethod


class BaseGoalsRepository:
    @abstractmethod
    async def save_goal() -> None: ...
    @abstractmethod
    async def get_all_user_goals() -> None: ...
    @abstractmethod
    async def update_goal() -> None: ...
    @abstractmethod
    async def get_goal_attrs() -> None: ...
    @abstractmethod
    async def delete_goal() -> None: ...
